openapi: 3.0.0
info:
  title: Client API
  version: '1.0'
  license:
    name: Apache 2.0
  description: "A Client's API for an open-source PlatformIO remote device management  "
  contact:
    name: nightuser
    url: 'https://github.com/nightuser/re-pio-openapi/'
servers:
  - url: 'http://localhost:3000'
paths:
  /device/list:
    get:
      summary: Device List
      tags:
        - Device
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
        '401':
          description: Unauthorized
      operationId: get-device-list
      description: Get the list of available devices
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: ''
  '/device/{deviceId}/monitor':
    parameters:
      - schema:
          type: integer
          format: int32
          minimum: 0
        name: deviceId
        in: path
        required: true
        description: Device ID
    get:
      summary: Device Monitor
      tags:
        - Device
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the device
                  socketAddr:
                    type: string
                    description: URL to the WebSocket
      operationId: get-device-id-monitor
      parameters: []
      description: 'Get a socket to the serial monitor of the specified device  '
  /run:
    parameters: []
    get:
      summary: Run
      tags:
        - Run
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebSocketURI'
              examples: {}
        '404':
          description: Unknown target
      operationId: get-run-target
      parameters:
        - schema:
            type: integer
            minimum: 0
            format: int32
          in: query
          name: deviceId
          description: "ID of the device. If empty and user has only one device, then it's used. Otherwise, the eror is returned."
        - schema:
            type: string
          in: query
          name: target
          description: Target to run on the device
      description: Runs target on the device
components:
  schemas:
    Device:
      title: Device
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
          description: ID of the device
        name:
          type: string
          description: Optional fancy name of the device
      required:
        - id
      description: A generic device description
      x-tags:
        - Device
    WebSocketURI:
      title: WebSocketURI
      type: object
      properties:
        address:
          type: string
      description: An address of the WebSocket
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://example.com/oauth2/authorize'
          tokenUrl: 'https://example.com/oauth2/token'
          refreshUrl: 'https://example.com/oauth2/refresh'
          scopes:
            all: ''
      description: ''
security: []
tags:
  - name: Device
  - name: Run
